# Generated by Django 5.1.4 on 2024-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedmodel',
            name='mtl_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='processedmodel',
            name='obj_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
